# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ASMLMonitoring

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrasmlmonitoring.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ab2d2e36decf40ef97886274ccb40526 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3535a71fea4e47789cf7019661b956c3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrasmlmonitoring.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ab2d2e36decf40ef97886274ccb40526 }}/asmlmonitoringapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ASMLMonitoring'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_379fe205104c4d429fd76568a1273a6d }}
        images: 'acrasmlmonitoring.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ab2d2e36decf40ef97886274ccb40526 }}/asmlmonitoringapp:${{ github.sha }}'